dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run-script lint
  - npm run-script test-headless
  - npm run-script build -- --prod --base-href "/angular-dnd/"

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: dist/dnd-app
  on:
    branch: master
